package ninegroup.ninegame;

import android.annotation.TargetApi;
import android.net.Uri;
import android.os.Build;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

/**
 * Created by guilherme on 19/11/15.
 */
public class QuestionsHandler {

    // lista com o banco de perguntas totalmente organizado por categoria
    ArrayList<Question> nql1 = new ArrayList<>(); // nql significa normal question level
    ArrayList<Question> nql2 = new ArrayList<>();
    ArrayList<Question> nql3 = new ArrayList<>();
    ArrayList<Question> nql4 = new ArrayList<>();
    ArrayList<Question> nql5 = new ArrayList<>();
    ArrayList<Question> qcl1 = new ArrayList<>(); // qcl significa question to change level
    ArrayList<Question> qcl2 = new ArrayList<>();
    ArrayList<Question> qcl3 = new ArrayList<>();
    ArrayList<Question> qcl4 = new ArrayList<>();
    ArrayList<Question> qcl5 = new ArrayList<>();

    public QuestionsHandler() {
        nql1.add(new Question("1 - [FCC 2010 - TRT - 8� Regi�o(PA e AP)] Considere um sistema de controle de estoque com cadastramento de materiais e movimenta��o do estoque. S�o necess�rios os seguintes c�lculos autom�ticos: controlar o saldo, o ponto de reposi��o e o lote econ�mico. O cadastro de materiais � feito pelo almoxarife (respons�vel) e as requisi��es s�o feitas por todos os departamentos da empresa e ficam guardadas. A cada entrega de material, o almoxarife d� baixa na requisi��o (atendida) e, com isso, o sistema faz todos os c�lculos acima. A entrada de materiais tamb�m � feita pelo almoxarife, quando os c�lculos tamb�m s�o realizados. Os dados calculados devem ficar guardados tamb�m e o tempo de resposta de consultas feitas no cadastro de materiais n�o deve exceder a 5 milissegundos (ms).Considerado um requisito N�O funcional:","a) o saldo calculado.","b) o tempo de resposta m�ximo.","c) o ponto de reposi��o.","d) a requisi��o baixada.","e) o cadastramento de materiais.","B"));

        nql1.add(new Question("2 - [CESGRANRIO 2010 - PETROBR�S] O modelo de ciclo de vida em cascata","a) enfatiza a realiza��o sequencial das atividades do desenvolvimento de um produto de software.","b) enfatiza a comuni��o estreita com o cliente durante o desenvolvimento do produto de software.","c) envolve a ideia principal de criar um prot�tipo execut�vel e, por meio de transforma��es sucessivas, chegar ao sistema completamente implementado.","d) envolve a an�lise dos riscos envolvidos no desenvolvimento dos requisitos identificados para produto de software.","e) recomenda a gera��o de vers�es incompletas do sistema, que podem ser passadas para o usu�rio final, o que permite a retroalimenta��o do processo de desenvolvimento.","A"));

        nql1.add(new Question("3 - [CESGRANRIO 2010 - PETROBRAS] Uma das caracter�sticas do Processo Unificado (Unified Process) � ser dirigido a casos de uso. Nesse contexto, analise as afirma��es a seguir.O modelo de casos de uso representa o comportamento de um sistema, conforme percebido do ponto de vista externo a esse sistema. O modelo de classes conceituais de um sistema pode ser obtido a partir do modelo de casos de uso.A esse respeito, conclui-se que:","a) as duas afirma��es s�o verdadeiras e a segunda justifica a primeira.","b) as duas afirma��es s�o verdadeiras e a segunda n�o justifica a primeira.","c) a primeira afirma��o � verdadeira e a segunda � falsa.","d) a primeira afirma��o � falsa e a segunda � verdadeira.","e) as duas afirma��es s�o falsas.","B"));

        nql1.add(new Question("4 - [FCC 2013 - DPE-SP] No desenvolvimento de software, podem ser utilizados os chamados modelos evolucion�rios, cujo objetivo � lidar com produtos que possam evoluir ao longo do tempo. Assinale a alternativa que cont�m APENAS modelos evolucion�rios de desenvolvimento de software.","a) UML e de qualidade.","b) Componentes e arqu�tipo. ","c) Prototipagem e espiral. ","d) Redes de Petri e certifica��o.","e) Sem�ntico e valida��o.","C"));

        nql1.add(new Question("5 - [CESGRANRIO 2012 - CHESF] O processo de engenharia de requisitos engloba todas as atividades necess�rias para criar e manter um documento de requisitos do sistema e compreender os elementos de neg�cio que ser�o atendidos pelo software a ser desenvolvido, pertencendo a uma sequ�ncia l�gica de atividades que culminam em um documento de requisitos correto que inclui todas as necessidades do cliente.O primeiro passo necess�rio no processo de cria��o desse documento de requisitos deve ser a(o)","a) an�lise de viabilidade.","b) prototipagem do sistema.","c) gera��o de casos de teste.","d) design da aplica��o.","e) documento de gerenciamento de mudan�as.","A"));

        nql1.add(new Question("6 - [ESAF 2013 - DNIT] S�o pr�ticas recomendadas pelo Rational Unified Process:","a) Desenvolver software paulatinamente. Eliminar requisitos. Usar arquiteturas baseadas em componentes. Modelar software sequencialmente. Verificar a qualidade do software continuamente. Controlar as mudan�as de orienta��o.","b) Adquirir software aplicativo. Gerenciar os requisitos. Usar arquiteturas baseadas em especifica��es de pre�o. Modelar software analiticamente. Verificar a atualidade do software continuamente. Controlar as pend�ncias no software.","c) Desenvolver problemas iterativamente. Gerenciar os reposit�rios de requisitos. Usar enfoques baseados em componentes. Modelar software visualmente. Verificar a qualidade do software continuamente. Eliminar as mudan�as no software.","d) Desenvolver software interativamente com os patrocinadores. Desconsiderar requisitos complexos. Usar arquiteturas baseadas em software. Modelar software visualmente. Verificar a origem do software continuamente. Controlar as vari�veis no software.","e) Desenvolver software iterativamente. Gerenciar os requisitos. Usar arquiteturas baseadas em componentes. Modelar software visualmente. Verificar a qualidade do software continuamente. Controlar as mudan�as no software.","E"));

        nql1.add(new Question("7 - [FCC 2012 - TRT-6� REGI�O(PE)] Considere: � uma disciplina que se ocupa de todos os aspectos da produ��o de software, desde os est�gios iniciais de especifica��o do sistema at� a manuten��o desse sistema, depois que ele entrou em opera��o. Seu principal objetivo � fornecer uma estrutura metodol�gica para a constru��o de software com alta qualidade. A defini��o refere-se","a) ao ciclo de vida do software.","b) � programa��o orientada a objetos.","c) � an�lise de sistemas.","d) � engenharia de requisitos.","e) � engenharia de software.","E"));

        nql1.add(new Question("8 - [CESGRANRIO 2011 - FINEP] Em ordem cronol�gica, quais s�o as fases definidas no Processo Unificado (UP)?","a) Concep��o, Requisitos, Implementa��o e Testes","b) Concep��o, Elabora��o, Constru��o e Implanta��o","c) Concep��o, Elabora��o, Constru��o e Transi��o","d) Elabora��o, Concep��o, Constru��o e Transi��o","e) Elabora��o, Constru��o, Implementa��o e Transi��o","C"));

        nql1.add(new Question("9 - [FCC 2010 - AL-SP] S�o fases do Processo Unificado de desenvolvimento de software:","a) Concep��o e Transi��o.","b) Elabora��o e An�lise.","c) Concep��o e Implementa��o.","d) Projeto e Implementa��o.","e) An�lise e Projeto.","A"));

        nql1.add(new Question("10 - [FCC 2010 - MPE-RN] No Processo Unificado (UP), o fluxo de trabalho An�lise, tem forte concentra��o na fase de","a) Implementa��o.","b) Elabora��o.","c) Constru��o.","d) Concep��o.","e) Transi��o.","B"));

        nql1.add(new Question("11 - [FUNCAB 2010 - PRODAM-AM] Assinale a alternativa que N�O representa uma caracter�stica do Processo Unificado (UP) original, descrito no livro The Unified Software Development Process (1999).","a) Iterativo e incremental.","b) Centrado na arquitetura.","c) �gil.","d) Orientado por casos de uso.","e) Focado na mitiga��o precoce dos riscos.","C"));

        nql1.add(new Question("12 - [FCC 2011 - INFRAERO] Ramifica��o sequencial, bifurca��o concorrente e uni�o concorrente s�o","a) meios de associa��o entre classes na UML ou entidades no MER.","b) componentes do Diagrama de Atividades da UML.","c) componentes do Diagrama Entidade-Relacionamento.","d) componentes do Diagrama de Sequ�ncia da UML.","e) possibilidades de associa��o entre atores e casos de uso da UML.","B"));

        nql1.add(new Question("13 - [FCC 2010 - MPE-RN] Considere:I. Dirigido por caso de uso.II. Orientado por quatro workflows.III. Centrado em arquitetura.IV. Distribu�do em cinco fases.V. Iterativo e incremental.S�o caracter�sticas do Processo Unificado (UP) o que consta APENAS em","a) I, II e III.","b) I, II e IV.","c) I, III e V.","d) II, III e V.","e) III, IV e V.","C"));

        nql1.add(new Question("14 - [ESAF 2012 - CGU]A estrutura de decomposi��o do trabalho fornece uma refer�ncia para a atribui��o de tamanho, esfor�o, cronograma e responsabilidades e � utilizada como uma estrutura subjacente para planejar, organizar e controlar o trabalho executado no projeto. Esta estrutura de decomposi��o pode ser:","a) o relat�rio da An�lise de Pontos de Fun��o.","b) o tamanho estimado do sistema.","c) o plano de trabalho preliminar.","d) o ?pacote preliminar de trabalho? (preliminary work package)","e) a EAP do projeto.","E"));

        nql1.add(new Question("15 - [FUNRIO 2013 - INSS] O diagrama UML usado na modelagem dos fluxos de trabalho de um processo de neg�cio e na modelagem da l�gica de um caso de uso ou de uma opera��o complexa � o diagrama de","a) atividades.","b) comunica��o.","c) estados.","d) intera��es.","e) sequ�ncia.","A"));

        nql1.add(new Question("16 - [FCC 2011 - TRT-4� REGI�O(RS)] O teste de componentes compostos concentra-se, princi- palmente, em verificar se","a) a funcionalidade dos c�digos do componente aten- dem aos requisitos de neg�cio.","b) o sistema est� atingindo a carga projetada, quando processados todos os componentes em conjunto.","c) a interface de componente se comporta de acordo com sua especifica��o.","d) a vers�o dos componentes do sistema est� de acordo com os requisitos n�o funcionais.","e) a satura��o sist�mica aborta a execu��o de um ou mais componentes.","C"));

        nql1.add(new Question("17 - [CETAP 2010 - AL-RR] Durante o processo de desenvolvimento de software, � necess�rio garantir que o software em desenvolvimento esteja satisfazendo os requisitos. Isto � realizado atrav�s de processos de teste do software. Selecione das seguintes alternativas, a CORRETA.","a) Os testes de software s�o feitos comparando se o n�mero de linhas de c�digo aumentou desde a �ltima revis�o.","b) Os testes de software do tipo caixa preta verificam se o c�digo est� bem documentado e os nomes das vari�veis declaradas s�o claros.","c) Os testes de software funcionais verificam a velocidade de conex�o do sistema com a base de dados.","d) Os testes n�o funcionais verificam se o c�digo fonte n�o tem erro de sintaxe.","e) Os testes unit�rios verificam o funcionamento de uma se��o espec�fica de c�digo, tais como uma fun��o ou uma classe.","E"));

        nql1.add(new Question("18 - [FCC 2010 - TRT-20� REUNI�O(SE)] No contexto da estrat�gia para o teste de um projeto, os est�gios de teste desempenham um papel importante. O teste que � aplicado a componentes do modelo de implementa��o para verificar se os fluxos de controle e de dados est�o cobertos e funcionam conforme o esperado, � o teste","a) do desenvolvedor.","b) independente.","c) de integra��o.","d) de sistema.","e) unit�rio.","E"));

        nql1.add(new Question("19 - [FGV 2010 - FIOCRUZ] Um tipo de teste de sistemas de software � tamb�m chamado de teste comportamental e focaliza os requisitos funcionais do software, permitindo ao engenheiro de software derivar conjuntos de condi��es de entrada que v�o exercitar plenamente todos os requisitos funcionais de um programa. Esse tipo de teste tende a ser aplicado durante os �ltimos est�gios do teste e tenta encontrar erros em fun��es incorretas ou omitidas, de interfaces, de estrutura de dados ou de acesso � base de dados externa, de comportamento ou desempenho de inicia��o e t�rmino. Al�m disso, � um tipo de teste que despreza, de prop�sito, a estrutura de controle, sendo a aten��o focalizada no dom�nio da informa��o. Esse tipo � conhecido por teste:","a) caixa-preta.","b) caixa-branca.","c) de fluxo de dados.","d) de caminho b�sico.","e) de l�gica composta.","A"));

        nql1.add(new Question("20 - [ESAF 2010 - CVM] S�o axiomas em risco","a) � imposs�vel testar um programa completamente. Teste de software � um exerc�cio baseado em certezas. Quanto menos bugs forem encontrados, mais bugs existir�o.","b) � poss�vel testar um programa completamente. Teste de software n�o pode ter riscos. Quanto mais breaks forem encontrados, mais breaks existir�o.","c) � imposs�vel testar um programa completamente. Teste de software � um exerc�cio baseado em risco. Quanto mais bugs forem encontrados, mais bugs existir�o.","d) � imposs�vel testar um programa que tenha riscos. Teste de software deve ser feito pelos seus desenvolvedores. Todos os bugs encontrados ser�o consertados.","e) � imposs�vel testar um programa parcialmente. Teste de software aplica-se unicamente a ambientes sem risco. Quanto mais bugs forem encontrados, menos bugs existir�o.","C"));

        nql2.add(new Question("1 - [FCC 2011 - TRT- 24� REGI�O(MS)] Considere:I. Um produtor ou consumidor de informa��es que resida fora dos limites do sistema a ser modelado.II. Um transformador de informa��es que resida dentro dos limites do sistema a ser modelado.III. Um m�todo de decomposi��o sucessiva, da mais abstrata para a mais granular vis�o de processos do sistema a ser modelado.Na an�lise estruturada, I, II e III correspondem, respectivamente, a","a) Fluxo de Dados, Processo e Top-Down.","b) Dep�sito de Dados, Entidade, Bottom-Up.","c) Entidade Externa, Processo e Bottom-Up.","d) Entidade Externa, Fluxo de Dados, Top-Down.","e) Entidade Externa, Processo, Top-Down.  Tachar alternativa.","E"));

        nql2.add(new Question("2 - [CESGRANRIO 2010 - PETROBR�S] Em metodologias de desenvolvimento de software, tem-se que","a) as 6 fases da Unified Process (UP) s�o: Concep��o, Projeto L�gico, Codifica��o, Projeto F�sico, Testes e Manuten��o.","b) a Extreme Programming (XP) � uma metodologia complexa, complementar ao Unified Process (UP), concebida para sistemas de alto desempenho que exigem trabalho extremo de defini��o de requisitos muito bem definidos e isolados de mudan�as.","c) a Rational Unified Process (RUP) procura dar um enfoque menor � documenta��o, valorizando mais a comunica��o oral; j� a Extreme Programming (XP) utiliza todos os artefatos da UML2.0 para usar como componente de entrada e sa�da.","d) a Rational Unified Process (RUP) possui pr�ticas em engenharia de software e sugest�es de uso de ferramentas automatizadas que possibilitam acelerar a implementa��o do CMMI n�vel 2 e criar uma base consistente para o CMMI n�vel 3.","e) a Rational Unified Process (RUP) � usada para desenvolver software de forma sequencial cont�nua, sem retroalimenta��o ou repeti��es evolutivas, e onde o produto s� � verificado e testado no final da �ltima fase.","D"));

        nql2.add(new Question("3 - [CESGRANRIO 2010 - PETROBR�S] A an�lise de risco no RUP � algo constante nas diversas fases do processo de desenvolvimento. Em cada uma das fases, o foco da ger�ncia de riscos se diferencia em fun��o do objetivo de cada fase. Assim, a manipula��o dos riscos est� relacionada, na fase de","a) an�lise, ao refinamento do modelo de requisitos e � sua poss�vel altera��o.","b) constru��o, � instala��o e distribui��o do produto no ambiente do cliente.","c) transi��o, � log�stica, uma vez que � a fase que envolve o maior n�mero de profissionais.","d) requisitos, � modelagem de neg�cio.","e) elabora��o, a quest�es t�cnicas, envolvendo a arquitetura escolhida.","E"));

        nql2.add(new Question("4 - [CESGRANRIO 2010 - PETROBR�S] Testar � uma disciplina de suma import�ncia para a engenharia de software. A literatura divide os tipos de testes em duas grandes categorias: teste de caixa preta e teste de caixa branca. Sobre esta classifica��o, pode-se afirmar queI - testes de interfaces s�o classificados como de caixa branca;II - testes de caixa preta s�o tamb�m chamados de teste comportamental, onde o foco s�o os requisitos funcionais do software;III - testes de caixa preta s�o complementares aos testes de caixa branca, uma vez que contemplam diferentes classes de erros.� correto o que se afirma em","a) I, apenas.","b) I e II, apenas.","c) I e III, apenas.","d) II e III, apenas.","e) I, II e III.","D"));

        nql2.add(new Question("5 - [INFRAERO 2011 - FCC] Em rela��o � Engenharia de Software, � INCORRETO afirmar:","a) O design de software, ao descrever os diversos aspectos que estar�o presentes no sistema quando constru�do, permite que se fa�a a avalia��o pr�via para garantir que ele alcance os objetivos propostos pelos interessados.","b) A representa��o de um design de software mais simples para representar apenas as suas caracter�sticas essenciais busca atender ao princ�pio da abstra��o.","c) Iniciar a entrevista para obten��o dos requisitos de software com perguntas mais gen�ricas e finalizar com perguntas mais espec�ficas sobre o sistema � o que caracteriza a t�cnica de entrevista estruturada em funil.","d) No contexto de levantamento de requisitos, funcionalidade � um dos aspectos que deve ser levado em conta na abordagem dos requisitos funcionais.","e) A representa��o � a linguagem do design, cujo �nico prop�sito � descrever um sistema de software que seja poss�vel construir.","E"));

        nql2.add(new Question("6 - [POSCOMP 2010] A UML (Unified Modeling Language) � uma linguagem padr�o para a elabora��o da estrutura de projetos que pode ser empregada para a visualiza��o, a especifica��o, a constru��o e a documenta��o de artefatos. No contexto da UML, um relacionamento � uma conex�o entre itens, representado graficamente como um caminho, com tipos diferentes de linhas para diferenciar os tipos de relacionamento. Com base no enunciado e nos conhecimentos sobre o tema, correlacione os tipos de relacionamentos e suas respectivas descri��es.(A) Associa��o.(B) Depend�ncia.(C) Generaliza��o.I. � um relacionamento de utiliza��o, determinando que um item usa as informa��es e servi�os de outro item, mas n�o necessariamente o inverso.II. � um relacionamento entre itens gerais e tipos mais espec�ficos desses itens.III. � um relacionamento estrutural que especifica objetos de um item conectados a objetos de outro item. A partir deste relacionamento, � poss�vel navegar do objeto de uma classe at� o objeto de outra classe e vice-versa.Assinale a alternativa que cont�m a associa��o correta.","a) I-A; II-B; III-C.","b) I-B; II-A; III-C.","c) I-B; II-C; III-A.","d) I-C; II-B; III-A.","e) I-C; II-A; III-B.","C"));

        nql2.add(new Question("7 - [POSCOMP 2013]Embora existam muitas abordagens para o desenvolvimento r�pido de software, elas compartilham algumas caracter�sticas fundamentais.Sobre essas caracter�sticas compartilhadas, assinale a alternativa correta.I. Esses processos de desenvolvimento r�pido requerem que os requisitos estejam todos especificados completamente para, em seguida, projetar, construir e testar o sistema.II. O software n�o � desenvolvido como uma �nica unidade, mas como uma s�rie de incrementos, onde cada incremento inclui uma nova ou novas funcionalidades do sistema (software).III. Os usu�rios finais e outros stakeholders do sistema s�o envolvidos na especifica��o e na avalia��o de cada vers�o (incremento do software). Eles podem propor altera��es ao software e novos requisitos a serem implementados em vers�es posteriores do software.IV. S�o m�todos de desenvolvimento incremental em que os incrementos, inclu�dos em uma nova vers�o do sistema, s�o disponibilizados aos clientes a cada duas ou tr�s semanas, por exemplo.Assinale a alternativa correta.","a) Somente as afirmativas I e II s�o corretas.","b) Somente as afirmativas I e IV s�o corretas.","c) Somente as afirmativas III e IV s�o corretas.","d) Somente as afirmativas I, II e III s�o corretas.","e) Somente as afirmativas II, III e IV s�o corretas.","E"));

        nql2.add(new Question("8 - [FUNRIO 2013 - MPOG] Considere o seguinte problema encontrado em projetos de desenvolvimento de software:�Projetos reais raramente seguem um fluxo sequencial. Apesar de um modelo linear poder acomodar a itera��o, ele o faz indiretamente. Como resultado, as modifica��es podem causar confus�o � medida que a equipe de projeto prossegue.� Esse � um dos problemas que s�o algumas vezes encontrados quando � aplicado o modelo de desenvolvimento","a) em cascata. ","b) �gil. ","c) espiral. ","d) incremental. ","e) unificado. ","A"));

        nql2.add(new Question("9 - [FCC 2015 - TRT-3� REGI�O(MG)] Um t�cnico de TI est� trabalhando em um projeto de desenvolvimento de software que utiliza metodologias �geis e est� acompanhando as hist�rias de usu�rios, que descrevem as funcionalidades que o software deve ter e","a) podem ser utilizadas para definir os testes unit�rios, mas n�o testes de aceita��o.","b) devem ser implementadas, cada uma, em at� 8 semanas.","c) precisam refletir os aspectos t�cnicos do software, n�o apenas a vis�o dos envolvidos.","d) devem ser escritas segundo o ponto de vista do analista de sistemas.","e) servem ao mesmo prop�sito de casos de uso, mas n�o s�o a mesma coisa.","E"));

        nql2.add(new Question("10 - [FCC 2015 - TRE-RR] Os modelos �geis de desenvolvimento N�O","a) reconhecem que modifica��es representam um risco e rejeitam aquelas em est�gios avan�ados do desenvolvimento, pr�ximos da entrega da vers�o final.","b) ressaltam a import�ncia de equipes auto-organizadas, que t�m controle sobre o trabalho que executam, encorajando estruturas e a��es que tornam a comunica��o mais f�cil.","c) enfatizam a entrega r�pida de software que satisfa�a o cliente e o adotam como parte da equipe para eliminar a dist�ncia entre �n�s e eles�.","d) satisfazem os princ�pios do Manifesto para o Desenvolvimento �gil de Software, inclusive a simplicidade.","e) acreditam que a entrega de software funcionando com frequ�ncia, a cada 2 semanas at� 2 meses, � a principal medida de progresso do desenvolvimento.","A"));

        nql2.add(new Question("11 - [FCC 2014 - TJ-AP] Um analista judici�rio est� participando de um debate sobre metodologias �geis a serem utilizadas no Tribunal de Justi�a do Amap�. Ele afirma corretamente que","a) o XP � uma metodologia adequada para equipes grandes que desenvolvem software baseado em requisitos precisos e que se modificam raramente. Entre suas caracter�sticas est�o reuni�es di�rias e feedback constante.","b) o FDD busca o desenvolvimento por funcionalidade. Pode atuar bem em conjunto com o Scrum, pois quando o Scrum atuar com foco no gerenciamento do projeto, o FDD pode atuar no processo de desenvolvimento.","c) a MDA � uma abordagem em que modelos abrangentes s�o criados depois que o c�digo-fonte est� escrito, de forma a validar os modelos �geis que guiam os esfor�os de desenvolvimento.","d) um ponto em comum entre o XP e o FDD � que ambos defendem o desenvolvedor como �nico respons�vel pelo m�dulo que este desenvolve. Al�m disso, recomendam entregas e contatos mensais com o cliente.","e) no MDD a implementa��o do c�digo � feita em dupla, de forma a procurarem identificar erros sint�ticos e sem�nticos, pensando em como melhorar o c�digo que est� sendo implementado.","B"));

        nql2.add(new Question("12 - [FCC 2014 - TRT-13� REGI�O(PB)] Fl�vio pretende desenvolver um software seguindo os est�gios do modelo em cascata proposto por Sommerville, em raz�o de pondera��es que faz em rela��o a outros modelos quanto � solu��o de um problema que se apresenta. Desta forma ele definiu em seu cronograma, na ordem apresentada pelo autor, as seguintes etapas do ciclo de vida de software:","a) Projeto de sistema e software; Defini��o de requisitos; Implementa��o e teste de unidade; Integra��o e teste de sistema; Opera��o e manuten��o.","b) Projeto de sistema e software; Engenharia de software; Integra��o e teste de sistema; An�lise de requisitos funcionais e t�cnicos; Opera��o e manuten��o; Implementa��o e teste de unidade.","c) Projeto de sistema e software; An�lise de requisitos; Engenharia de requisitos; Implanta��o; Testes de sistemas; Opera��o e manuten��o.","d) Defini��o de requisitos; Engenharia de requisitos; Integra��o e teste de sistema; Projeto de sistema e software; Implementa��o e teste de unidade; Opera��o e manuten��o; Integra��o e teste de sistema.","e) Defini��o de requisitos; Projeto de sistema e software; Implementa��o e teste de unidade; Integra��o e teste de sistema; Opera��o e manuten��o.","E"));

        nql2.add(new Question("13 - [FCC 2012 - MPE-PE]Os requisitos n�o funcionais n�o est�o diretamente ligados aos servi�os espec�ficos oferecidos pelo sistema a seus usu�rios. Eles podem estar relacionados �s propriedades emergentes do sistema, como confiabilidade, tempo de resposta e ocupa��o de �rea, entre outros. Dentre os tipos de requisitos n�o funcionais, � poss�vel destacar os requisitos de produto, organizacionais e externos. Dentre os requisitos de produto, podemos citar os requisitos","a) de efici�ncia e de confian�a.","b) cont�beis e de desempenho.","c) legais e de usabilidade.","d) reguladores e de prote��o.","e) legais e cont�beis.","A"));

        nql2.add(new Question("14 - [FCC 2012 - TST] Na Engenharia de Requisitos, o gerente de requisitos","a) acompanha e monitora a��es durante a verifica��o do software, sendo este o processo que garante o atendimento aos requisitos informados pelo usu�rio final.","b) possui autonomia para realizar altera��es no projeto para garantir que o software seja bem constru�do e atenda as necessidades da equipe de desenvolvimento.","c) mant�m atualizados os requisitos junto ao usu�rio final e a equipe de desenvolvimento, a fim de obter sucesso no processo de homologa��o do software, atendendo as necessidades e expectativas.","d) classifica os requisitos em diferentes tipos, sendo os do tipo funcional relacionados com o custo e confiabilidade do software e os do tipo n�o-funcional relacionados com os casos de uso.","e) obt�m o comprometimento dos integrantes da equipe de desenvolvimento de software para o cumprimento do processo de software.","C"));

        nql2.add(new Question("15 - [ESAF 2013 - DNIT] O objetivo principal da An�lise de Pontos de Fun��o �:","a) verificar a fundamenta��o da funcionalidade de um software ou aplicativo.","b) medir a oportunidade qualitativa de um software ou aplicativo.","c) medir a funcionalidade de um software ou aplicativo.","d) simplificar a complexidade funcional de um software ou aplicativo.","e) medir a funcionalidade dos pontos de acesso � operacionaliza��o de um software ou aplicativo.","C"));

        nql2.add(new Question("16 - [FUNRIO 2013 - MPOG] Na An�lise de Pontos de Fun��o, fatores de ajustamento s�o usados para fornecer uma indica��o da complexidade do problema. Tais fatores de ajustamento s�o baseados em 14 caracter�sticas gerais do sistema como, por exemplo, Comunica��o de Dados e Desempenho. Qual das alternativas abaixo N�O � uma caracter�stica geral do sistema usada no c�lculo do valor do fator de ajustamento?","a) Entrada de dados online.","b) Reusabilidade.","c) Facilidade operacional.","d) Processamento complexo.","e) Disponibilidade 24x7.","E"));

        nql2.add(new Question("17 - [ESAF 2012 - CGU] S�o exemplos de ALI:","a) Arquivos de �ndices.","b) Arquivos tempor�rios, de trabalho ou de classifica��o.","c) Arquivos de backup.","d) Arquivos de mensagens de erro desde que mantidos pela aplica��o.","e) Arquivos introduzidos exclusivamente em fun��o da tecnologia utilizada.","D"));

        nql2.add(new Question("18 - [FCC 2012 - TST] A Engenharia de Software","a) � uma �rea da computa��o que visa abordar de modo sistem�tico as quest�es t�cnicas e n�o t�cnicas no projeto, implanta��o, opera��o e manuten��o no desenvolvimento de um software.","b) consiste em uma disciplina da computa��o que aborda assuntos relacionados a t�cnicas para a otimiza��o de algoritmos e elabora��o de ambientes de desenvolvimento.","c) trata-se de um ramo da TI que discute os aspectos t�cnicos e emp�ricos nos processos de desenvolvimento de sistemas, tal como a defini��o de artefatos para a modelagem �gil.","d) envolve um conjunto de itens que abordam os aspectos de an�lise de mercado, concep��o e projeto de software, sendo independente da engenharia de um sistema.","e) agrupa as melhores pr�ticas para o concep��o, projeto, opera��o e manuten��o de artefatos que suportam a execu��o de programas de computador, tais como as t�cnicas de armazenamento e as estruturas em mem�ria principal.","A"));

        nql2.add(new Question("19 - [FCC 2010 - TRE-AM] A Engenharia de Software","a) n�o tem como m�todo a abordagem estruturada para o desenvolvimento de software, pois baseia-se exclusivamente nos modelos de software, nota��es, regras e t�cnicas de desenvolvimento.","b) se confunde com a Ci�ncia da Computa��o quando ambas tratam do desenvolvimento de teorias, fundamenta��es e pr�ticas de desenvolvimento de software.","c) tendo como foco apenas o tratamento dos aspectos de constru��o de software, subsidia a Engenharia de Sistemas no tratamento dos sistemas baseados em computadores, incluindo hardware e software.","d) tem como foco principal estabelecer uma abordagem sistem�tica de desenvolvimento, atrav�s de ferramentas e t�cnicas apropriadas, dependendo do problema a ser abordado, considerando restri��es e recursos dispon�veis.","e) segue princ�pios, tais como, o da Abstra��o, que identifica os aspectos importantes sem ignorar os detalhes e o da Composi��o, que agrupa as atividades em um �nico processo para distribui��o aos especialistas.","D"));

        nql2.add(new Question("20 - [CESPE 2013 - TRE-MS] Por meio de diagramas da UML, � poss�vel capturar diferentes vis�es do sistema. Assinale a op��o que apresenta o diagrama de um comportamento din�mico do sistema.","a) diagrama de casos de uso.","b) diagrama de objetos.","c) diagrama de componentes.","d) diagrama de implanta��o.","e) diagrama de classes  Tachar alternativa.","A"));

        nql3.add(new Question("1 - [CETAP 2010 - AL-RR] Analise os seguintes enunciados relacionados aos componentes da linguagem UML e marque a alternativa CORRETA.I- Os diagramas de casos de uso t�m como objetivo ilustrar a intera��o entre elementos (atores) e funcionalidades do sistema;II- O modelo de classes de dom�nio representa as classes no dom�nio do neg�cio em quest�o e n�o leva em considera��o restri��es inerentes � tecnologia a ser utilizada na solu��o;III- Uma classe em um diagrama de classes � definida por um nome, uma lista de atributos (n�o obrigat�ria) e uma lista de opera��es (n�o obrigat�ria);IV- O modelo de intera��o pode ser descrito utilizando diagramas de componentes ou diagramas de estados;V- Os pacotes s�o mecanismos de agrupamento gen�rico e podem ser utilizados para agregar casos de uso, classes e alguns outros tipos de elementos.","a) Os enunciados I, II e IV est�o corretos.","b) Somente o enunciado I est� correto.","c) Os enunciados I, IV e V est�o corretos.","d) Os enunciados I, II, III e V est�o corretos.","e) Todos os enunciados est�o corretos.","D"));

        nql3.add(new Question("2 - [CESGRANRIO 2010 - PETROBR�S] O RUP, Processo Unificado da Rational, � dividido em fases e atividades, sendo que","a) a primeira fase do RUP que corresponde ao levantamento de requisitos � tamb�m chamada de concep��o.","b) o in�cio da fase de an�lise depende do levantamento de requisitos, que devem ser est�veis e bem documentados.","c) ao t�rmino da fase de concep��o, um dos artefatos produzidos � um documento de vis�o refinado.","d) na fase de constru��o, a atividade de an�lise j� foi conclu�da e o foco � a implementa��o.","e) cada fase � dividida em uma ou mais itera��es e, ao final de cada intera��o, artefatos s�o necessariamente validados.","E"));

        nql3.add(new Question("3 - [CESGRANRIO 2010 - PETROBR�S] Em rela��o ao Unified Process (UP), considere as seguintes atividades:I - utiliza��o como um \"framework\" que se baseia em componentes, o qual modela os processos de forma iterativa e incremental;II - atua��o no direcionamento do desenvolvimento de v�rias maneiras, criando mecanismos, por exemplo, para a valida��o da arquitetura do sistema;III - utiliza��o dos artefatos de constru��o de sistema para facilitar a reusabilidade dos componentes do sistema.A(s) atividade(s) necess�ria(s) para transformar requisitos do usu�rio em um sistema de software � (s�o)","a) II, apenas.","b) I e II, apenas.","c) I, e III, apenas.","d) II e IIII, apenas.","e) I, II, III.","E"));

        nql3.add(new Question("4 - [FGV 2010 - BANDESC] De acordo com Pressman, a engenharia de software � baseada em camadas, com foco na qualidade. Essas camadas s�o:","a) m�todos, processo e teste.","b) ferramentas, m�todos e processo.","c) m�todos, constru��o, teste e implanta��o.","d) planejamento, modelagem, constru��o, valida��o e implanta��o.","e) comunica��o, planejamento, modelagem, constru��o e implanta��o.","B"));

        nql3.add(new Question("5 - [POSCOMP 2014] Sobre requisitos de software, considere as afirmativas a seguir.I. A descoberta de falhas e inadequa��es, assim como a falta de detalhes, podem alterar os requisitos de um produto.II. Funcionalidades, interfaces externas e desempenho s�o algumas caracter�sticas que devem ser inclu�das na especifica��o dos requisitos de um software.III. Requisitos como custo, cronograma de entregas e crit�rios de verifica��o e valida��o s�o considerados aspectos gerenciais do projeto, por isso devem ser exclu�dos das especifica��es dos requisitos de software.IV. O usu�rio chave � definido como uma pessoa capacitada para implementar as funcionalidades b�sicas do produto, baseando-se nos requisitos.Assinale a alternativa correta.","a) Somente as afirmativas I e II s�o corretas.","b) Somente as afirmativas I e IV s�o corretas.","c) Somente as afirmativas III e IV s�o corretas.","d) Somente as afirmativas I, II e III s�o corretas.","e) Somente as afirmativas II, III e IV s�o corretas.","D"));

        nql3.add(new Question("6 - [POSCOMP 2014] Sobre testes de software, assinale a alternativa correta.","a) O m�todo da caixa preta objetiva executar um subconjunto de testes previamente executados.","b) Os testes de aceita��o t�m como objetivo a verifica��o de um elemento que possa ser tratado, logicamente, como uma unidade de implementa��o.","c) Os testes de integra��o objetivam verificar se as unidades implementadas funcionam em conjunto com as unidades implementadas em itera��es anteriores.","d) Os testes de unidade objetivam validar o produto, verificando se ele atende �s funcionalidades requisitadas.","e) Os testes de regress�o objetivam determinar os defeitos da estrutura interna do produto, exercitando os poss�veis caminhos de execu��o.","C"));

        nql3.add(new Question("7 - [POSCOMP 2010] A Engenharia de Requisitos � um processo que envolve todas as atividades exigidas para criar e manter o documento de requisitos de sistema. Sobre a Engenharia de Requisitos, considere as afirmativas a seguir.I. A Engenharia de Requisitos, como todas as outras atividades de Engenharia de Software, precisa ser adaptada �s necessidades do processo, do projeto, do produto e do pessoal que est� fazendo o trabalho.II. No est�gio de levantamento e an�lise dos requisitos, os membros da equipe t�cnica de desenvolvimento do software trabalham com o cliente e os usu�rios finais do sistema para descobrir mais informa��es sobre o dom�nio da aplica��o, que servi�os o sistema deve oferecer, o desempenho exigido do sistema, as restri��es de hardware, entre outras informa��es.III. Na medida em que a informa��o de v�rios pontos de vista � coletada, os requisitos emergentes s�o consistentes.IV. A valida��o de requisitos se ocupa de mostrar que estes realmente definem o sistema que o cliente deseja. Ela � importante porque a ocorr�ncia de erros em um documento de requisitos pode levar a grandes custos relacionados ao retrabalho.Assinale a alternativa correta.","a) Somente as afirmativas I e II s�o corretas.","b) Somente as afirmativas I e III s�o corretas.","c) Somente as afirmativas III e IV s�o corretas.","d) Somente as afirmativas I, II e IV s�o corretas.","e) Somente as afirmativas II, III e IV s�o corretas.","D"));

        nql3.add(new Question("8 - [CESGRANRIO 2011 - BNDES] O acoplamento de conte�do acontece quando, entre dois m�dulos, um referencia o interior do outro. Esses dois m�dulos podem estar acoplados por mais de uma forma.Desse modo, o acoplamento desses m�dulos ser� definido pela(o)","a) coes�o existente entre esses m�dulos.","b) portabilidade das atividades de um m�dulo para outro.","c) troca de mensagens de suas funcionalidades.","d) pior tipo de acoplamento por eles apresentado.","e) tamanho das instru��es comuns ao acoplamento.","D"));

        nql3.add(new Question("9 - [FCC 2015 - TRT-3� REGI�O(MG)] Com rela��o ao Scrum, considere:I. O Product Owner, ou dono do produto, � respons�vel por garantir que o Scrum seja entendido e aplicado. Faz isso para garantir que o Time Scrum adere � teoria, pr�ticas e regras do Scrum. � um servo-l�der para o Time Scrum.II. O Scrum Master � o respons�vel por maximizar o valor do produto e do trabalho do Time de Desenvolvimento. Como isso � feito pode variar amplamente nas organiza��es, Times Scrum e indiv�duos.III. O cora��o do Scrum � a Sprint, um time-boxed de um m�s ou menos, durante o qual um �Pronto\", vers�o incremental potencialmente utiliz�vel do produto, � criado.Est� correto o que consta APENAS em","a) I e II.","b) III.","c) II e III.","d) II.","e) I e III.","B"));

        nql3.add(new Question("10 - [FCC 2014 - TJ-AP] O Scrum � um framework �gil para suportar o desenvolvimento e manuten��o de produtos complexos. Nesta abordagem,","a) a Equipe de Desenvolvimento � composta pelo Product Owner, o Time Scrum e o Scrum Master. A Equipe � auto- organiz�vel e escolhe qual a melhor forma para completar seu trabalho.","b) o Scrum Master � o respons�vel por maximizar o valor do produto e do trabalho do Time Scrum. � a �nica pessoa respons�vel por gerenciar o Backlog do Produto.","c) o tamanho ideal do Time Scrum, respons�vel pela codifica��o dos testes, � de 3 componentes. Se houver mais de 5 integrantes � exigida muita coordena��o e n�o vai funcionar.","d) o trabalho a ser realizado na Sprint � planejado na reuni�o de planejamento da Sprint, que � um time-box de 8 horas para uma Sprint de 1 m�s de dura��o. Para Sprints menores, este evento deve ser proporcionalmente menor.","e) a Revis�o da Sprint � uma oportunidade para o Time Scrum inspecionar a si pr�prio e criar um plano para melhorias a serem aplicadas na pr�xima Sprint. Esta � uma reuni�o time-boxed de 5 horas para uma Sprint de 2 meses.","D"));

        nql3.add(new Question("11 - [AOCP 2012 - BRDE] Sobre a Obten��o de requisitos de um sistema proposto, abaixo analise as assertivas e assinale a alternativa que aponta a(s) correta(s).I. Fontes de informa��es durante a fase de obten��o de requisitos incluem documenta��o, stakeholders de sistema e especifica��es de sistemas similares.II. A intera��o com os stakeholders neste processo de d� por meio de entrevistas e observa��es, podendo ser utilizado sen�rio e at� mesmo prot�tipos para auxiliar nesta obten��o.III. Os stakeholders variam de usu�rios finais do sistema a gerentes e envolvidos externos.IV. Fontes de requisitos como stakeholders, dom�nios e outros sistemas podem ser representados como pontos de vista do sistema, em que cada ponto de vista apresenta um subconjunto de requisitos do novo sistema.","a) Apenas I e II.","b) Apenas I e III.","c) Apenas II e III.","d) Apenas II, III e IV.","e) I, II, III e IV.","E"));

        nql3.add(new Question("12 - [FCC 2012 - MPE-AP] Uma vez que um sistema tenha sido instalado e seja usado regularmente, inevitavelmente surgir�o novos requisitos que, ent�o, dever�o ser avaliados pela ger�ncia de requisitos. Dentre os motivos do surgimento de novos requisitos, considere:I. Ap�s a instala��o, o ambiente t�cnico e de neg�cios do sistema sempre muda. Como exemplo, um novo hardware pode ser introduzido, pode ser necess�rio fazer a interface do sistema com outros sistemas, as prioridades do neg�cio podem mudar etc.II. As pessoas que pagam por um sistema e os usu�rios desse sistema raramente s�o os mesmos. Clientes do sistema imp�em requisitos devido a restri��es or�ament�rias e organizacionais, os quais podem entrar em conflito com os requisitos do usu�rio final, e, ap�s a entrega, novos recursos podem ser adicionados.III. Geralmente, sistemas de grande porte t�m uma comunidade de diversos usu�rios, com diferentes requisitos e prioridades, que podem ser conflitantes ou contradit�rios.Est� correto o que se afirma em","a) I, II e III.","b) II e III, apenas.","c) I e II, apenas.","d) I e III, apenas.","e) II, apenas.","A"));

        nql3.add(new Question("13 - [FCC 2012 - TRE-SP] Sobre a an�lise de pontos por fun��o, considere:I. � um m�todo de contagem padr�o capaz de medir as funcionalidades de um sistema sobre o ponto de vista do desenvolvedor.II. A contagem sem ajustes (UFPC - unadjusted function point count) reflete as funcionalidades cont�veis espec�ficas disponibilizadas pelo sistema ou aplica��o para o usu�rio.III. � uma ferramenta para ajudar usu�rios a determinar os benef�cios de um pacote de aplicativos para sua empresa por meio de contagem das funcionalidades que especificamente atendem seus requerimentos.Est� correto o que consta em","a) II, apenas.","b) I e II, apenas.","c) I e III, apenas.","d) II e III, apenas.","e) I, II e III.","D"));

        nql3.add(new Question("14 - [INSTITUTO CIDADES 2012 - TCM-GO] Analise:I. Medir a funcionalidade solicitada pelo usu�rio, antes do projeto de software, de forma a estimar seu tamanho e seu custo;II. Medir a aplicabilidade destes projetos em situa��es externas ao ambiente de implanta��o original de forma a padroniz�-los para todos os tipos de clientes, independente de sua �rea de atua��o.III. Medir projetos de desenvolvimento e manuten��o de software, independentemente da tecnologia utilizada na implementa��o, de forma a acompanhar sua evolu��o;IV. Medir a funcionalidade recebida pelo usu�rio, ap�s o projeto de software, de forma a verificar seu tamanho e custo, comparando-os com o que foi originalmente estimado.S�o considerados objetivos da an�lise de pontos de fun��o:","a) I, II e III, somente;","b) I, II e IV, somente;","c) II, III e IV, somente;","d) I, III e IV, somente;","e) I e IV, somente.","D"));

        nql3.add(new Question("15 - [FCC 2012 - TCE-AP] Um dos primeiros passos para efetuar a contagem por pontos de fun��o de um sistema, � definir o tipo de contagem que ser� efetuado. Esses tipos se dividem em","a) entrada, sa�da e processamento.","b) requisitos, elabora��o e testes.","c) desenvolvimento, manuten��o e aplica��o.","d) controle, mecanismo e processamento","e) l�gico, f�sico e modelagem.","C"));

        nql3.add(new Question("16 - [ESAF 2012 - CGU] Cada Arquivo L�gico Interno e cada Arquivo de Interface Externa devem ser classificados com rela��o � sua complexidade funcional com base em:","a) N�mero de Tipos de Dados, N�mero de Tipos de Registros.","b) N�mero de Tipos de Arquivos, N�mero de Tipos de Registros.","c) N�mero de Tipos de Dados, N�mero de Tipos de Consultas.","d) N�mero de Tipos de Campos, N�mero de Tipos de Arquivos.","e) N�mero de Tipos de Tabelas, N�mero de Tipos de Campos.","A"));

        nql3.add(new Question("17 - [CESPE 2013 - TRE-MS] De acordo com o RUP (Rational Unified Process), a fase de concep��o consiste em","a) desenvolver os componentes do software.","b) converter as bases de dados.","c) identificar os atores que interagem com o sistema.","d) construir um prot�tipo execut�vel.","e) descrever a arquitetura do software.","C"));

        nql3.add(new Question("18 - [FUNRIO 2013 - MPOG] No processo unificado de desenvolvimento de software, qual � a fase em que o planejamento do projeto � completado, o dom�nio do neg�cio � analisado e os requisitos do sistema s�o ordenados considerando-se prioridade e risco?","a) Concep��o.","b) Elabora��o.","c) Constru��o.","d) Transi��o.","e) Produ��o.","B"));

        nql3.add(new Question("19 - [FGV 2009 - MEC] A lista a seguir descreve atividades a serem realizadas durante a an�lise e o projeto estruturado de sistemas. I. Definir mensagens de entrada e sa�da II. Definir mensagens das fun��es internas III. Decompor o sistema em processos primitivos IV. Especificar processos primitivos As atividades acima descritas representam tarefas a serem desenvolvidas na modelagem:","a) Est�tica.","b) Funcional.","c) Din�mica.","d) Orientada a Metas.","e) Orientada a Objetos.","B"));

        nql3.add(new Question("20 - [ESAF 2010 - SUSEP] Na contagem de Arquivos L�gicos Referenciados (ALR)","a) n�o se deve contar ALR para Arquivo L�gico Interno mantido.","b) deve-se contar dois ALR caso haja acesso a arquivo de mensagens de erros.","c) deve-se contar um ALR caso haja acesso apenas a arquivos criptografados.","d) deve-se contar um ALR para cada par de Arquivos L�gicos Internos que s�o lidos e mantidos por entidades externas distintas.","e) deve-se contar apenas um ALR para cada Arquivo L�gico Interno que � lido e mantido por uma entidade externa.","E"));

        nql4.add(new Question("1 - [IADES 2013 - EBSERH] De acordo com o padr�o de qualidade ISO 9126, s�o identifcados seis atributos fundamentais da qualidade. Sobre o tema, assinale a alternativa correta.","a) A usabilidade diz respeito � quantidade de tempo, que o software fca dispon�vel para uso.","b) A efci�ncia � o grau com que o software satisfaz �s necessidades declaradas.","c) A disponibilidade � o grau de tempo em que o software permanece no ar para utiliza��o.","d) A portabilidade � a facilidade com a qual um software pode ser transportado de um ambiente para outro.","e) A confdencialidade � a capacidade de manter partes do software, em sigilo, s� sendo permitido o conhecimento, por parte de pessoas autorizadas.","D"));

        nql4.add(new Question("2 - [FCC 2012 - TCE-AP] Em rela��o a requisitos de sistemas, considere:I. O modo como um sistema deve reagir a certas entradas e o comportamento em que o sistema deve ter em certas situa��es e, em alguns casos, especificar o que o sistema n�o deve fazer, s�o chamados de requisitos n�o-funcionais.II. As restri��es aos servi�os ou fun��es de um sistema, como, por exemplo, processos de desenvolvimento ou utiliza��o de padr�es, s�o requisitos de funcionamento do sistema ou requisitos funcionais.III. Requisitos que vem do dom�nio da aplica��o do sistema e refletem caracter�sticas ou restri��es para aquele dom�nio s�o chamados de requisitos de dom�nio e podem ser requisitos funcionais e/ou n�o-funcionais.Est� correto o que se afirma em","a) III, apenas.","b) I, II e III.","c) I e II, apenas.","d) II e III, apenas.","e) I, apenas.","A"));

        nql4.add(new Question("3 - [IADES 2013 - EBSERH] Sempre que � encontrado um erro, no processo de teste de software, � necess�rio relatar o incidente. Para isso, deve- se defnir os relat�rios necess�rios, para acompanhar o progresso do projeto de teste, segundo a norma IEEE 829- 1998. Os relat�rios de teste que a IEEE sugere s�o:","a) teste unit�rio, teste de sistema e teste de aceita��o.","b) log de teste, incidente de teste e sum�rio de teste.","c) documento de teste, caso de teste e teste de sistema.","d) teste de sistema, teste de integra��o e casos de teste","e) casos de teste, casos de usos e teste de sistema.","B"));

        nql4.add(new Question("4 - [IADES 2013 - EBSERH] A atividade de teste � composta por alguns elementos essenciais, que auxiliam na formaliza��o desta atividade. A afrma��o serve para selecionar e avaliar casos de teste, de forma a aumentar as possibilidades de provocar falhas ou, quando isso n�o ocorre, estabelecer um n�vel elevado de confan�a na corre��o do produto, refere-se a qual elemento da atividade de teste?","a) Caso de teste.","b) Procedimento de teste.","c) Crit�rio de cobertura dos testes.","d) Crit�rio de teste.","e) Crit�rio de gera��o de casos de Teste.","D"));

        nql4.add(new Question("5 - [FUNRIO 2013 - INSS] Suponha que um sistema tenha uma contagem total estimada de 1.000 pontos de fun��o n�o ajustados. De acordo com a An�lise de Pontos de Fun��o, qual a faixa de valores poss�veis de pontos de fun��o ajustados, para esse sistema, ap�s a aplica��o dos Fatores de Ajuste de Valor (Value Adjustment Factors)?","a) de 500 a 1.500.","b) de 650 a 1.350.","c) de 700 a 1.300.","d) de 860 a 1.140.","e) de 900 a 1.100.","B"));

        nql4.add(new Question("6 - [FCC 2012 - TRT-11� REGI�O(AM)] Segundo a IFPUG em rela��o � m�trica do software por an�lise por pontos de fun��o, considere:I. An�lise por pontos de fun��o executa a medi��o do software determinando a quantidade de funcionalidades que o software fornece ao usu�rio baseado principalmente na arquitetura l�gica.II. O objetivo da an�lise por pontos de fun��o � medir as funcionalidades que o usu�rio requisita e recebe e, tamb�m, medir o desenvolvimento e manuten��o do software com depend�ncia na implementa��o utilizada pela empresa.III. O processo de contagem dos pontos de fun��o deve ser simples o suficiente para minimizar a sobrecarga do processo de medida e consistente dentre os v�rios projetos e organiza��es.Est� correto o que se afirma em","a) I e II, apenas.","b) I e III, apenas.","c) II e III, apenas.","d) III, apenas.","e) I, II e III.","B"));

        nql4.add(new Question("7 - [FUNVERSA 2009 - IPHAN] Assim como a Engenharia de Software, existe tamb�m na �rea de inform�tica a chamada Ci�ncia da Computa��o. Assinale a alternativa que melhor apresenta a diferen�a entre Engenharia de Software e Ci�ncia da Computa��o.","a) A Ci�ncia da Computa��o tem como objetivo o desenvolvimento de teorias e fundamenta��es. J� a Engenharia de Software se preocupa com as pr�ticas de desenvolvimento de software.","b) A Engenharia de Software trata da cria��o dos sistemas de computa��o (softwares) enquanto a Ci�ncia da Computa��o est� ligada ao desenvolvimento e cria��o de componentes de hardware.","c) A Engenharia de Software trata dos sistemas com base em computadores, que inclui hardware e software, e a Ci�ncia da Computa��o trata apenas dos aspectos de desenvolvimento de sistemas.","d) A Ci�ncia da Computa��o trata dos sistemas com base em computadores, que inclui hardware e software, e a Engenharia de Software trata apenas dos aspectos de desenvolvimento de sistemas.","e) A Ci�ncia da Computa��o destina-se ao estudo e solu��o para problemas gen�ricos das �reas de rede e banco de dados e a Engenharia de Software restringe- se ao desenvolvimento de sistemas.","A"));

        nql4.add(new Question("8 - [FUNVERSA 2009 - IPHAN] A Engenharia de Software resume-se em um conjunto de t�cnicas utilizadas para o desenvolvimento e manuten��o de sistemas computadorizados, visando produzir e manter softwares de forma padronizada e com qualidade. Ela obedece a alguns princ�pios como (1) Formalidade, (2) Abstra��o, (3) Decomposi��o, (4) Generaliza��o e (5) Flexibiliza��o. Assinale a alternativa que apresenta conceito correto sobre os princ�pios da Engenharia de Software.","a) A flexibiliza��o � o processo que permite que o software possa ser alterado, sem causar problemas para sua execu��o.","b) A formalidade � a maneira usada para resolver um problema, de forma gen�rica, com o intuito de poder reaproveitar essa solu��o em outras situa��es semelhantes.","c) A generaliza��o preocupa-se com a identifica��o de um determinado fen�meno da realidade, sem se preocupar com detalhes, considerando apenas os aspectos mais relevantes.","d) Pelo princ�pio da decomposi��o, o software deve ser desenvolvido de acordo com passos definidos com precis�o e seguidos de maneira efetiva.","e) A abstra��o � a t�cnica de se dividir o problema em partes, de maneira que cada uma possa ser resolvida de uma forma mais espec�fica.","A"));

        nql4.add(new Question("9 - [CONSULPLAN 2007 - CHESF] Segundo Pressman (1995), Engenharia de Software � o estabelecimento e uso de s�lidos princ�pios de engenharia para que se possa obter economicamente um software que seja confi�vel e que funcione eficientemente em m�quinas reais, abrangendo um conjunto de tr�s elementos fundamentais (m�todos, ferramentas e procedimentos). Assinale a alternativa INCORRETA:","a) M�todos de Engenharia de Software proporcionam os detalhes de ?como fazer? para construir o software.","b) As ferramentas proporcionam apoio automatizado ou semi-automatizado aos m�todos.","c) Procedimentos constituem o elo de liga��o dos m�todos e das ferramentas e possibilitam o desenvolvimento racional e oportuno de software.","d) M�todos envolvem um amplo conjunto de tarefas que incluem: planejamento e estimativa de projeto, an�lise de requisitos de software e sistemas, projeto de estrutura de dados, arquitetura de programa e algoritmo de processamento, codifica��o, teste e manuten��o.","e) Ferramentas s�o roteiros para o desenvolvimento de software.","E"));

        nql4.add(new Question("10 - [FCC 2008 - METR�-SP] Os paradigmas das linguagens de programa��o, interpretados como \"meios\" onde problemas s�o resolvidos, apresentam diferentes significados para \"programa\" e para a \"m�quina que executa o programa\". Nesse sentido, no meio funcional,","a) o computador � entendido como uma m�quina que obedece ordens e o programa como uma prescri��o de solu��o para o problema.","b) uma express�o � avaliada e seu resultado, em geral, � armazenado em uma c�lula de mem�ria representada por uma vari�vel.","c) a ordem de avalia��o de suas express�es de mapeamento � controlada por seq�encia��o e itera��o.","d) os programas n�o estabelecem exatamente \"como\" um resultado deve ser computado, mas, descrevem fatos e regras que podem levar a m�quina � dedu��o desse c�lculo.","e) o computador atua como uma m�quina que avalia fun��es e o programa consiste da defini��o e composi��o de fun��es.","E"));

        nql4.add(new Question("11 - [ESAF 2004 - CGU] Analise as seguintes afirma��es relativas � Ger�ncia de Projetos de Software:I. A prototipagem � o processo de construir um sistema rapidamente com o objetivo de distribuir para os usu�rios uma vers�o final do mesmo sem que este tenha passado pelas fases de teste.II. Uma WBS (Work Breakdown Structure) � uma t�cnica que consiste na decomposi��o hier�rquica de um projeto e na representa��o dessa estrutura resultante em forma de um diagrama em �rvore.III. A t�cnica WBS, quando aplicada a um processo de prototipagem, tem como resultado final uma �nica unidade, que representa o sistema como uma caixa preta que impossibilita o acompanhamento eficaz do processo de desenvolvimento.IV. Os gr�ficos de Gantt basicamente representam as atividades na forma de barras. Esses gr�ficos s�o utilizados tanto para dar uma vis�o geral do planejamento quanto para permitir um acompanhamento eficaz do processo de desenvolvimento.Est�o corretos os itens:","a) I e II.","b) II e III.","c) III e IV.","d) I e III.","e) II e IV.","E"));

        nql4.add(new Question("12 - [CONSULPLAN 2006 - INB] Modelo Ambiental e Modelo Comportamental s�o modelos componentes do(a):","a) An�lise Orientada a Objetos.","b) UML.","c) An�lise Essencial.","d) Diagrama de Entidades e Relacionamentos.","e) An�lise de Requisitos.","C"));

        nql4.add(new Question("13 - [NCE-UFRJ 2005 - BNDES] Observe as seguintes assertivas sobre o Modelo Essencial de um sistema de informa��o:I - O Modelo Essencial � composto pelo Modelo Ambiental e pelo Modelo Comportamental.II - O Modelo Ambiental descreve as respostas do sistema a cada um dos eventos externos.III - O Modelo Comportamental � descrito pelo diagrama de contexto.As assertivas corretas s�o:","a) somente I;","b) somente II;","c) somente III;","d) somente I e II;","e) I, II e III.","A"));

        nql4.add(new Question("14 - [INSTITUTO CIDADES 2012 - TCM-GO] Sobre o processo unificado de desenvolvimento de software marque a alternativa incorreta:I. O processo unificado de desenvolvimento de software � o conjunto de atividades necess�rias para transformar requisitos do usu�rio em um sistema de software, baseado em componentes.II. Os aspectos que distinguem o processo unificado s�o capturados em tr�s conceitos chaves: direcionado a casos de uso; iterativo e incremental; com foco em desempenho.III. H� v�rios benef�cios em se adotar um processo iterativo controlado, entre os quais podemos destacar a redu��o dos riscos envolvendo custos a um �nico incremento.IV. O final de uma fase � marcado por um ponto de verifica��o. Um dos prop�sitos destes pontos de verifica��o � que permitem a monitora��o do progresso dos trabalhos.","a) II, somente;","b) I e II, somente;","c) I, II e III, somente;","d) II, III e IV, somente.","e) Todas as afirma��es;","A"));

        nql4.add(new Question("15 - [FCC 2011 - TRT-23� REGU�AI(MT)] No Unified Process os pap�is n�o s�o pessoas; eles descrevem como as pessoas se comportam no neg�cio e quais s�o as responsabilidades que elas t�m. Nesse sentido, um Desenvolvedor desempenha os pap�is de","a) Analista de Sistemas, Designer de Neg�cios e Revisor de Requisitos.","b) Analista de Teste, Implementador e Designer de Interface de Usu�rio.","c) Revisor de Requisitos, Analista de Teste e Revisor do Projeto.","d) Implementador, Integrador e Designer.","e) Gerente de Teste, Gerente de Projeto e Designer.","D"));

        nql4.add(new Question("16 - [FCC 2013 - TRT-9� REGI�O(PR)] No grupo de processos de inicia��o do projeto, definido no PMBoK, h� um que visa desenvolver o termo de abertura do projeto. Nessa etapa � desenvolvido um documento que autoriza formalmente o in�cio do projeto. Esse documento pode conter a necessidade do neg�cio, a defini��o do produto, o nome do gerente e a justificativa da import�ncia do projeto.O documento descrito no texto � chamado de","a) Scope Statement.","b) Service Contract.","c) Project Charter.","d) Open Contract.","e) Service Agreement.","C"));

        nql4.add(new Question("17 - [FCC 2012 - TRE-SP] Sobre ger�ncia de projetos, � INCORRETO afirmar que","a) n�o existe necessariamente uma rela��o direta entre o valor cobrado por um sistema e o custo de seu desenvolvimento.","b) o tempo necess�rio para a finaliza��o de um projeto � sempre proporcional ao n�mero de pessoas alocadas a ele","c) entre os fatores que alteram a produtividade de um software est�o o ambiente de trabalho e o processo de desenvolvimento.","d) o pre�o de um software frequentemente � adequado para se fechar um contrato com o cliente e as funcionalidades oferecidas s�o, ent�o, ajustados para se adaptar a esse pre�o.","e) existem diversas t�cnicas de estimativa de custos de sistema e, ao se preparar a estimativa de custo, diversas t�cnicas devem ser utilizadas.","B"));

        nql4.add(new Question("18 - [ESAF 2012 - CGU] O ponto de partida para o planejamento do projeto � o","a) Plano de trabalho.","b) Descritivo das funcionalidades.","c) Escopo","d) Documento de autoriza��o do projeto.","e) Documento de demanda.","C"));

        nql4.add(new Question("19 - [FCC 2011 - TRT-23� REGI�O(MT)] A disciplina Gerenciamento de Projeto do RUP tem por finalidade fornecer um framework para gerenciamento deI. Projetos espec�ficos de software.II. Riscos.III. Or�amento.IV. Contratos.Est� correto o que consta em","a) I e II, apenas.","b) III e IV, apenas.","c) I, II e III, apenas.","d) II, III e IV, apenas.","e) I, II, III e IV.","A"));

        nql4.add(new Question("20 - [VUNESP 2010 - CEAGESP] Uma das �reas de Conhecimento do PMBOK 2004 � a Ger�ncia de Custo do Projeto. Considere as seguintes afirma��es sobre essa �rea:I. o Planejamento Organizacional � um de seus processos;II. uma das entradas de seu processo Estimativa de Custos � o WBS;III. uma das sa�das de seu processo Controle de Custos s�o as M�tricas de Qualidade.As afirma��es corretas sobre a �rea de Conhecimento Ger�ncia de Custo do Projeto s�o as contidas em","a) I, apenas.","b) II, apenas.","c) I e III, apena","d) II e III, apenas.","e) I, II e III.","B"));

        nql5.add(new Question("1 - [CESGRANRIO 2010 - PETROBR�S] Em rela��o aos diagramas utilizados na UML 2.0,","a) o diagrama de estrutura composta serve para ilustrar a arquitetura de um sistema, mostrando o agrupamento de suas classes.","b) o diagrama de pacotes enfatiza a apresenta��o das classes do ambiente modelado, de acordo com um conjunto de eventos.","c) o diagrama de implanta��o � usado para sistemas distribu�dos e permite apresentar a topologia de uma rede de m�quinas e qual processo cada m�quina vai rodar.","d) o diagrama de colabora��o tem o objetivo de mostrar como as mensagens entre os objetos s�o trocadas no decorrer do tempo para a realiza��o de uma opera��o.","e) o diagrama de sequ�ncia mostra o contexto de uma intera��o, inclusive os objetos e seus relacionamentos pertinentes a uma intera��o particular.","C"));

        nql5.add(new Question("2 - [FCC 2010 - TRE-RS]Sobre a engenharia de software, considere:I. Atualmente todos os problemas na constru��o de software de alta qualidade no prazo e dentro do or�amento foram solucionados.II. Ao longo dos �ltimos 50 anos, o software evoluiu de um produto de ind�stria para um ferramental especializado em solu��o de problemas e an�lise de informa��es espec�ficas.III. Todo projeto de software � iniciado por alguma necessidade do neg�cio.IV. O intuito da engenharia de software � fornecer uma estrutura para a constru��o de software com alta qualidade.Est� correto o que consta em","a) III e IV, somente.","b) II e III, somente.","c) I, II e IV, somente.","d) II, III e IV, somente.","e) I, II, III e IV.","A"));

        nql5.add(new Question("3 - [FCC 2012 - TJ-PE] Em rela��o a Qualidade e Teste de Software, quando um produto � previamente testado e enviado para uma nova avalia��o, considere:I. Todas as partes alteradas nos documentos, funcionalidades e informa��es devem ser testadas como se fosse um produto novo.II. Todas as partes inalteradas que sejam influenciadas pelas partes alteradas ou por mudan�as em um requerido sistema (de acordo com os conhecimentos espec�ficos do testador) devem ser testadas por amostragem.III. Todas as outras partes que n�o foram alteradas ou influenciadas pelas altera��es, devem ser testadas como sendo um novo produto.Est� correto o que se afirma em","a) I, apenas.","b) I, II e III.","c) II, apenas.","d) I e III, apenas.","e) III, apenas.","A"));

        nql5.add(new Question("4 - [FCC 2010 - TRE-AM] Para se garantir a qualidade dos processos, v�rios passos devem ser tomados, entre eles:I. Gerenciar os requisitos, identificando quais s�o as principais necessidades do software, levanto em conta tanto os requisitos funcionais quanto os n�o funcionais.II. Acompanhar o projeto de software para que se possa ter uma vis�o bem realista do progresso do projeto, sendo poss�vel tomar a��es eficazes quando o desempenho software se desviar de forma significativa dos planos do projeto.III. Gerenciar a configura��o do software para estabelecer e manter a integridade dos produtos do projeto ao longo do ciclo de vida do software para dar maior seguran�a ao desenvolvedor e permitir maior controle de desenvolvimento.IV. Desenvolver um processo padr�o para ser gerenciado e revisado, Identificar os pontos fortes e fracos do processo de desenvolvimento e planejar atividades de melhoramento.� correto o que se afirma em","a) II e IV, apenas .","b) I, II e III, apenas.","c) II, III e IV, apenas.","d) I e III, apenas.","e) I, II, III e IV.","E"));

        nql5.add(new Question("5 - [IADES 2013 - EBSERH] A fase de elabora��o dos testes de software � uma das partes mais importantes, no desenvolvimento de um software.Sobre o teste de caixa branca,assinale a alternativa correta.","a) Teste feito pela equipe de testadores de software.","b) Teste executado pelo usu�rio fnal do software.","c) Teste realizado, na fase de concep��o do software.","d) Teste executado, ap�s a implanta��o do software.","e) Teste feito pelo pr�prio programador que verifca, se o c�digo que foi constru�do, � funcional.","E"));

        nql5.add(new Question("6 - [FEPESE 2010 - SEFAZ-SC] Identifique as alternativas corretas a respeito de engenharia reversa.1. Descompiladores s�o usados para obter o c�digo fonte de um software a partir de seu c�digo bin�rio.2. Ofuscadores de c�digo efetuam a cifragem de c�digos bin�rios de programas com o intuito de impedir a sua descompila��o.3. Atrav�s de t�cnicas de engenharia reversa, � poss�vel obter diagramas UML de um programa a partir de seu c�digo fonte.4. Descompila��o de c�digo e esteganografia s�o duas t�cnicas frequentemente usadas para realizar a engenharia reversa de sistemas computacionais.Assinale a alternativa que indica todas as afirmativas corretas.","a) S�o corretas apenas as afirmativas 1 e 3.","b) S�o corretas apenas as afirmativas 1 e 4.","c) S�o corretas apenas as afirmativas 2 e 3.","d) S�o corretas apenas as afirmativas 1, 2 e 4.","e) S�o corretas apenas as afirmativas 2, 3 e 4.","A"));

        nql5.add(new Question("7 - [FCC 2010 - DPE-SP] A Engenharia de SoftwareI. n�o visa o desenvolvimento de teorias e fundamenta��es, preocupando-se unicamente com as pr�ticas de desenvolvimento de software.II. tem como foco o tratamento dos aspectos de desenvolvimento de software, abstraindo-se dos sistemas baseados em computadores, incluindo hardware e software.III. tem como m�todos as abordagens estruturadas para o desenvolvimento de software que incluem os modelos de software, nota��es, regras e maneiras de desenvolvimento.IV. segue princ�pios, tais como, o da Abstra��o, que identifica os aspectos importantes sem ignorar os detalhes e o da Composi��o, que agrupa as atividades em um �nico processo para distribui��o aos especialistas.� correto o que se afirma em","a) III e IV, apenas.","b) I, II, III e IV.","c) I e II, apenas.","d) I, II e III, apenas.","e) II, III e IV, apenas.","D"));

        nql5.add(new Question("8 - [CESGRANRIO 2006 - EPE] O gerente de um projeto foi informado, por sua equipe, que uma determinada atividade de caminho cr�tico apresenta um valor esperado de 38 dias e existe cerca de 95,44% de chance de a mesma ser conclu�da entre 30 e 46 dias. Sabendo-se que foi utilizado PERT para as estimativas apresentadas, qual das op��es a seguir apresenta, em dias, uma poss�vel configura��o para as estimativas otimista, mais prov�vel e pessimista, respectivamente, para esta atividade?","a) 20, 39 e 52.","b) 22, 39 e 50.","c) 22, 40 e 46.","d) 24, 40 e 44.","e) 25, 40 e 43.","C"));

        nql5.add(new Question("9 - [ESAF 2004 - CGU] Considere a defini��o de projeto como \"um empreendimento tempor�rio com o objetivo de criar um produto ou servi�o �nico\" e analise as seguintes afirma��es relativas � Ger�ncia de Projetos de Software:I. O termo \"Tempor�rio\" n�o est� aplicado corretamente j� que a dura��o de um projeto � indeterminada, tornando projetos em esfor�os continuados.II. O termo \"�nico\" significa que o produto ou servi�o produzido � de alguma forma diferente de todos os outros produtos ou servi�os semelhantes.III. O termo \"Tempor�rio\" significa que cada projeto tem um in�cio e um fim muito bem definidos. Chega-se ao fim do projeto quando os seus objetivos foram alcan�ados ou quando torna-se claro que os objetivos do projeto n�o ser�o ou n�o poder�o mais ser atingidos.IV. Os projetos devem envolver todas as unidades da organiza��o, mas n�o podem atravessar as fronteiras organizacionais.Est�o corretos os itens:","a) I e II.","b) II e III.","c) III e IV.","d) I e III.","e) II e IV.","B"));

        nql5.add(new Question("10 - [FGV 2009 - MEC] Modelo Essencial � o modelo do que o sistema tem que fazer, de forma a satisfazer os requisitos do utilizador, com o m�nimo poss�vel de informa��o sobre como o sistema deve ser implementado. As alternativas a seguir apresentam as ferramentas que fazem parte do Modelo Essencial, � exce��o de uma. Assinale-a.","a) Diagrama Entidade Relacionamentos.","b) DFD de Contexto.","c) DFD por Eventos.","d) Normaliza��o.","e) Fluxograma.","E"));

        nql5.add(new Question("11 - [CESGRANRIO 2008 - PETROBR�S] Uma pr�tica gerencial adotada em diversas organiza��es, que aumenta a visibilidade dos projetos para os executivos, facilitando sua prioriza��o e a detec��o de problemas, bem como prevenindo a realiza��o de projetos que n�o estejam alinhados com a organiza��o � a(o)","a) An�lise de riscos.","b) Gerenciamento de Portif�lios de Projetos.","c) Gerenciamento Integrado de Projetos.","d) Gerenciamento Total da Qualidade.","e) PERT - Program Evaluation and Review Technique.","B"));

        nql5.add(new Question("12 - [CESGRANRIO 2012 - PETROBR�S] No Processo Unificado, a(o)","a) vers�o pronta para instala��o sobrev�m a cada itera��o terminada.","b) fase de Constru��o tem, normalmente, um n�mero maior de itera��es que as demais.","c) dura��o de uma itera��o � fixada antes do seu in�cio, n�o podendo ultrapassar duas semanas.","d) objetivo da fase de Elabora��o � construir um prot�tipo que demonstre a viabilidade da solu��o proposta, que ser� implementada na fase de Constru��o.","e) Documento da Arquitetura de Software (SAD) deve estar pronto antes do t�rmino da fase de Elabora��o.","B"));

        nql5.add(new Question("13 - [FCC 2009 - PGE-RJ] No processo Conceber Novo Projeto da disciplina Gerenciamento de Projeto, a atividade Iniciar Projeto � realizada ap�s a aprova��o do artefato","a) plano de desenvolvimento de software.","b) plano de intera��o.","c) vis�o.","d) caso de neg�cio.","e) lista de risco.","D"));

        nql5.add(new Question("14 - [FCC 2007 - TRE-SE] O gerente do projeto deseja gerenciar o tempo do projeto. Assim, dentre as ferramentas e t�cnicas que pode usar no seq�enciamento de atividades encontra-se","a) o Flowcharting.","b) o Nivelamento Heur�stico dos Recursos.","c) a Medi��o de Desempenho.","d) o Modelo de Rede.","e) o Benchmarking.","D"));

        nql5.add(new Question("15 - [ESAF 2004 - CGU] Considere a defini��o de projeto como \"um empreendimento tempor�rio com o objetivo de criar um produto ou servi�o �nico\" e analise as seguintes afirma��es relativas � Ger�ncia de Projetos de Software:I. O termo \"Tempor�rio\" n�o est� aplicado corretamente j� que a dura��o de um projeto � indeterminada, tornando projetos em esfor�os continuados.II. O termo \"�nico\" significa que o produto ou servi�o produzido � de alguma forma diferente de todos os outros produtos ou servi�os semelhantes.III. O termo \"Tempor�rio\" significa que cada projeto tem um in�cio e um fim muito bem definidos. Chega-se ao fim do projeto quando os seus objetivos foram alcan�ados ou quando torna-se claro que os objetivos do projeto n�o ser�o ou n�o poder�o mais ser atingidos.IV. Os projetos devem envolver todas as unidades da organiza��o, mas n�o podem atravessar as fronteiras organizacionais.Est�o corretos os itens:","a) I e II","b) II e III","c) III e IV","d) I e III","e) II e IV","B"));

        nql5.add(new Question("16 - [FCC 2012 - TRT-11� REGI�O(AM)] N�O � uma t�cnica t�pica de teste de caixa preta:","a) teste de tabela de decis�o.","b) teste de todos os pares.","c) teste de integra��o.","d) teste de caso de uso.","e) tabelas de estado de transi��o.","C"));

        nql5.add(new Question("17 - [FCC 2012 - TRE-SP] Sobre desenvolvimento baseado em testes, considere:I. Este processo requer que desenvolvedores criem unidades de testes para definir os requisitos que um determinado c�digo deve conter. Estes testes devem ser criados assim que uma pequena parte funcional do c�digo esteja dispon�vel.II. Frequentemente s�o utilizados frameworks de teste pelos desenvolvedores como o xUnit ou jUnit para a cria��o de casos de teste automatizados.III. � importante que o c�digo escrito seja apenas projetado para passar o teste espec�fico. Nenhuma outra funcionalidade deve ser prevista ou permitida fora do escopo do teste em nenhum est�gio do processo.Est� correto o que consta em","a) I, apenas.","b) II, apenas.","c) I e III, apenas.","d) II e III, apenas.","e) I, II e III.","D"));

        nql5.add(new Question("18 - [FCC 2012 - TRT-6� REGI�O(PE)] Sobre testes de sistemas, considere:I. Testes de cen�rio s�o �teis pois podem garantir que n�o restam erros no sistema. Neste ponto diferem dos testes de componentes que apenas garantem a integridade de m�dulos isolados do sistema, mas n�o garantem que a totalidade do sistema est� isenta de erros.II. Testes de desenvolvimento incluem testes unit�rios, nos quais s�o testados objetos e m�todos espec�ficos; testes de componentes, nos quais s�o testados diversos grupos de objetos; testes de sistema, nos quais s�o testados sistemas parciais e sistemas completos.III. Os testes de usu�rio podem ser divididos em tr�s fases: teste alfa, em que os usu�rios do software trabalham com a equipe de desenvolvimento para efetuar testes no local do desenvolvedor; teste beta, em que um release de software � disponibilizado aos usu�rios para que possam experimentar e levantar os problemas descobertos com os desenvolvedores do sistema; teste de sistema, em que os clientes testam um sistema para decidir se ele est� pronto para ser implantado no ambiente de trabalho.Est� correto o que se afirma em","a) I, II e III.","b) II, apenas.","c) I e II, apenas.","d) III, apenas.","e) II e III, apenas.","B"));

        nql5.add(new Question("19 - [FASMIP-BA 2011 - MPE-BA] Identifique com V as afirmativas verdadeiras e com F, as falsas.( ) A an�lise de requisitos possibilita que o Engenheiro de Software especifique a fun��o e o desempenho do software.( ) Os testes de software s�o atividades de garantia da qualidade por si mesmo.( ) A seguran�a de software � uma atividade de garantia de qualidade de software que se concentra na identifica��o e avalia��o de casualidades em potencial que possam exercer um impacto negativo sobre o software e fazer com que todo o sistema falhe.A alternativa que cont�m a sequ�ncia correta, de cima para baixo, � a","a) F V F","b) F F V","c) V F V","d) V F F","e) V V V","C"));

        nql5.add(new Question("20 - [FESMIP-BA 2011 - MPE-BA] Identifique com V as afirmativas verdadeiras e com F, as falsas.( ) A confiabilidade pode ser medida diretamente e estimada, usando-se dados hist�ricos e de desenvolvimento.( ) Os testes de caixa preta focalizam a estrutura de controle do programa, sendo que os casos de teste s�o derivados para garantir que todas as instru��es do programa tenham sido exercitadas pelo menos uma vez durante os testes e que todas as condi��es l�gicas tenham sido exercitadas.( ) Os testes de caixa branca s�o projetados para validar os requisitos funcionais, sem se preocupar com o funcionamento interno de um programa.A alternativa que cont�m a sequ�ncia correta, de cima para baixo, � a","a) V V V","b) V V F","c) F F V","d) F V F","e) V F F","E"));

        qcl1.add(new Question("1 - [FCC 2012 - TJ-RJ] Dos diferentes modelos para o ciclo de vida de desenvolvimento de um software � correto afirmar que","a) o modelo em espiral � o mais simples e o mais antigo.","b) o modelo em cascata � o menos flex�vel e mais simples.","c) a fase de especifica��o de requisitos pode estar ausente do modelo.","d) a fase de implementa��o � sempre a �ltima do modelo.","e) o modelo em cascata � o mais recente e complexo.","B"));

        qcl1.add(new Question("2 - [FCC 2012 - TRE-CE] A an�lise de requisitos no desenvolvimento de sistemas especifica as funcionalidades (requisitos funcionais) e as propriedades (requisitos n�o-funcionais). � considerado um requisito n�o-funcional","a) uma informa��o na interface de entrada.","b) a notifica��o de inconsist�ncia de dado na tela.","c) um histograma na interface gr�fica do usu�rio.","d) a emiss�o de relat�rios fiscais.","e) a disponibilidade do sistema.","E"));

        qcl1.add(new Question("3 - [FCC 2012 - TJ-PE] Na engenharia de requisitos trata-se de uma t�cnica de elicita��o que ocorre em ambiente mais informal em que toda a id�ia deve ser levada em considera��o para a solu��o de um problema, sendo proibida a cr�tica a qualquer sugest�o dada, e encorajada, inclusive, a cria��o de ideias que pare�am estranhas ou ex�ticas:","a) Prototipa��o.","b) Entrevista.","c) Question�rio.","d) Brainstorming.","e) An�lise de protocolos.","D"));

        qcl1.add(new Question("4 - [FCC 2010 - MPE-RN]As pol�ticas de rastreabilidade de requisitos s�o decididas durante o est�gio de","a) agrega��o dos requisitos funcionais, apenas.","b) implementa��o do sistema, apenas.","c) implementa��o do sistema","d) elimina��o dos requisitos n�o funcionais.","e) gerenciamento de requisitos.","E"));

        qcl1.add(new Question("5 - [FCC 2015 - TRT-3� REGI�O(MG)] Um t�cnico de TI est� trabalhando em um projeto de desenvolvimento de software que utiliza o modelo Scrum, em que as funcionalidades a serem implementadas, na forma de hist�rias de usu�rios, s�o mantidas em uma lista denominada","a) product backlog.","b) sprint.","c) chaos list.","d) sprint burndown.","e) metaphor list.","A"));

        qcl1.add(new Question("6 - [IADES 2013 - EBSERH] Os testes de software s�o executados, usando os procedimentos e documentos de script de teste. Para que a fase de execu��o de teste, seja realizada com sucesso deve(m) ser executado(s):","a) os casos de uso","b) os diagramas de atividade","c) os casos de teste","d) os testes de Turing","e) o teste de COMA.","C"));

        qcl1.add(new Question("7 - [IADES 2013] Assinale a alternativa que n�o corresponde a um dos testes de software,realizados em softwares comerciais.","a) Teste de Sistema","b) Teste de valida��o.","c) Teste de integra��o.","d) Teste de volatilidade de requisitos.","e) Teste de unidade.","D"));

        qcl1.add(new Question("8 - [CESPE 2013 - TRE-MS] Assinale a op��o que apresenta uma das finalidades da an�lise de requisitos.","a) Gerar vers�es dos artefatos produzidos.","b) Prover o ambiente adequado para a organiza��o.","c) Documentar processos de neg�cio usando casos de uso de neg�cios.","d) Balancear objetivos em conflito entre os participantes do projeto.","e) Organizar, levantar e documentar funcionalidades e restri��es.","E"));

        qcl1.add(new Question("9 - [FCC 2010 - TRT-20� REGI�O(SE)] No desenvolvimento de sistemas, no �mbito das rela��es intermodulares entre as classes, diz-se que o programa est� bem estruturado quando h�","a) maior coes�o e maior acoplamento.","b) menor coes�o e maior acoplamento.","c) menor coes�o e menor acoplamento.","d) maior coes�o e menor acoplamento.","e) apenas coes�o ou apenas acoplamento.","D"));

        qcl1.add(new Question("10 - [FCC 2011 - TRE-RN] S�o produtos da fase de elabora��o do RUP:","a) documento de vis�o e produto de software integrado.","b) descri��o da arquitetura do software e lista de riscos revisada.","c) manual do usu�rio e base de dados operacionais convertidas.","d) lista de riscos revisada e base de dados operacionais convertidas.","e) produto de software integrado e descri��o da arquitetura do software.","B"));

        qcl2.add(new Question("1 - [CESGRANRIO 2011 - BNDES] Um gerente de projeto est� preocupado com o desempenho de um sistema de informa��o que est� prestes a ser implantado, uma vez que existe uma expectativa de acesso de muitos usu�rios. Que tipo de teste, mais especificamente, pode ser realizado para avaliar o desempenho desse sistema, dadas condi��es operacionais vari�veis, tais como n�mero de usu�rios e transa��es?","a) Carga.","b) Funcional.","c) Integra��o.","d) Unidade.","e) Usabilidade.","A"));

        qcl2.add(new Question("2 - [FCC 2011 - TRE-RN] Em rela��o � Refatora��o, � INCORRETO afirmar:","a) a exist�ncia ou n�o de testes automatizados no software � irrelevante.","b) utiliza fortemente conceitos de orienta��o a objeto.","c) melhora a estrutura interna do c�digo sem alterar seu comportamento externo.","d) evita a deteriora��o durante o ciclo de vida de um c�digo.","e) incrementa melhoria no entendimento do c�digo.","A"));

        qcl2.add(new Question("3 - [ESAF 2010 - CVM] Com Ferramentas de Gerenciamento de Projetos, o gerente de projeto pode definir uma","a) equipe de defini��o do trabalho (work definition team).","b) estrutura de apoio ao usu�rio (user support structure).","c) estrutura de divis�o do trabalho (work breakdown structure).","d) estrutura de divis�o de objetos (object breakdown structure).","e) metodologia de segmenta��o dos programas (program segmentation methodology).","C"));

        qcl2.add(new Question("4 - [FCC 2010 - MPE-RN] Caso particular de associa��o bin�ria utilizado para expressar um relacionamento todo-parte. Entretanto, a parte pode n�o ser exclusiva de um �nico todo. No diagrama de classes � uma","a) Generaliza��o.","b) Composi��o.","c) Estereotipagem.","d) Agrega��o.","e) Depend�ncia.","D"));

        qcl2.add(new Question("5 - [FCC 2012 - TJ-PE] S�o pr�ticas eficientes para revis�o de c�digo, EXCETO:","a) Revisar c�digo por, no m�ximo, 90 minutos por vez.","b) Revisar at� 500 linhas de c�digo por hora.","c) Adotar revis�es de c�digo com aux�lio de ferramentas.","d) Revisar at� 1000 linhas de c�digo por vez.","e) Decidir antecipadamente os objetivos do processo de revis�o de c�digo e como medir sua efetividade.","D"));

        qcl2.add(new Question("6 - [CESGRANRIO 2012 - CHESF] Dentre os atributos de um software de qualidade, incluem-se:","a) controlabilidade, dependabilidade e efici�ncia.","b) controlabilidade, efici�ncia e manutenibilidade.","c) efici�ncia, imutabilidade e manutenibilidade.","d) efici�ncia, manutenibilidade e usabilidade.","e) imutabilidade, manutenibilidade e usabilidade.","D"));

        qcl2.add(new Question("7 - [INSTITUTO CIDADES 2012 - TCM-GO] Identifique dentre as op��es abaixo o processo de engenharia de requisitos composto por quatro atividades de alto n�vel.","a) Prepara��o, especifica��o e documenta��o, afirma��o e implanta��o;","b) Identifica��o, an�lise e negocia��o, especifica��o e documenta��o, valida��o;","c) Levantamento e prepara��o, investiga��o, viabilidade, confirma��o;","d) Identifica��o, planejamento, atribui��o, valida��o;","e) An�lise e negocia��o, valida��o, observa��o, prepara��o.","B"));

        qcl2.add(new Question("8 - [CESGRANRIO 2012 - PETROB�S] Ao determinar os requisitos de um projeto, � necess�rio levantar os requisitos funcionais e os n�o funcionais.Os requisitos n�o funcionais","a) definem com detalhes exatamente o que deve ser implementado.","b) definem explicitamente as fun��es que o sistema n�o deve executar.","c) indicam os servi�os que o sistema deve prestar.","d) representam restri��es aos servi�os oferecidos pelo sistema.","e) s�o descri��es de que servi�os o sistema deve fornecer aos usu�rios.","D"));

        qcl2.add(new Question("9 - [FCC 2011 - TCE-PR] No processo de engenharia de requisitos, os tipos de requisitos de usu�rio e de sistema podem ser, respectivamente,","a) apenas funcionais; apenas n�o funcionais.","b) apenas n�o funcionais; apenas funcionais.","c) apenas funcionais; funcionais e n�o funcionais.","d) funcionais e n�o funcionais; apenas n�o funcionais.","e) funcionais e n�o funcionais; funcionais e n�o funcionais.","E"));

        qcl2.add(new Question("10 - [IADES 2013 - EBSERH] Assinale a alternativa correta, sobre automa��o de teste de software.","a) � a tarefa executada, pelos analistas de teste, tendo como objetivo descrever os fuxos dos UCs do Sistema.","b) Tem como principal tarefa, ajudar na concep��o do Software.","c) � um question�rio, aplicado para os usu�rios fnais do Sistema.","d) � ferramenta de instala��o de Software.","e) � a utiliza��o de um sistema, para controlar a execu��o dos testes de um Software.","E"));

        qcl4.add(new Question("1 - [CESGRANRIO 2010 - PETROBR�S] V�rias m�tricas de software s�o utilizadas para aferir a qualidade de um processo de software, dentre as quais podem-se destacar","a) Corretude, Manutenbilidade e Integridade.","b) Ponto de Fun��o, Usabilidade e Confiabilidade.","c) Complexidade Ciclom�tica, Corretude e Manutenbilidade.","d) Usabilidade, Confiabilidade e N� de Linhas de C�digo.","e) Usabilidade, Confiabilidade e Integridade.","A"));

        qcl4.add(new Question("2 - [ESAF 2010 - CVM] S�o informa��es que comp�em o gerenciamento de defeitos","a) Causa do defeito. Risco calculado. Interfaces. Informa��es do software. Provas e evid�ncias da exist�ncia do controle.","b) Identifica��o do defeito. Decomposi��o. Severidade. Interfaces. Provedores do software. Provas e evid�ncias da exist�ncia do defeito.","c) Dissemina��o. Severidade. Premissas. Risco de complexidade. Status. Pressupostos da exist�ncia do defeito.","d) Implica��es do defeito. Descri��o. Risco associado. Springs. Provas e evid�ncias da elimina��o do defeito.","e) Identifica��o do defeito. Prioridade. Status. Informa��es do software. Prova e evid�ncias da identi?ca��o do defeito.","E"));

        qcl4.add(new Question("3 - [IADES 2013 - EBSERH] Segundo Pressman (2011), a defni��o de defeito de software � um problema de qualidade encontrado.","a) somente ap�s a libera��o de uso do software para os usu�rios fnais.","b) antes de o software ser liberado aos usu�rios fnais.","c) na fase de revis�o.","d) na fase de levantamento de requisitos.","e) na fase de prototipa��o.","A"));

        qcl4.add(new Question("4 - [ESAF 2012 - CGU]S�o caracter�sticas gerais de sistema utilizadas para c�lculo do fator de ajuste:","a) Reutiliza��o, Taxa de recep��o de dados.","b) Atualiza��o off-line, Modifica��es facilitadas.","c) Modifica��es facilitadas, Processamento paralelo.","d) Entrada de dados off-line, Compatibilidade Web.","e) M�ltiplos locais, Processamento complexo.","E"));

        qcl4.add(new Question("5 - [FCC 2010 - TCM-PA] Os fluxos b�sicos de controle de um m�dulo s�o:","a) composi��o, intera��o e repeti��o.","b) repeti��o, sele��o e depend�ncia.","c) agrega��o, composi��o e sele��o.","d) sele��o, repeti��o e sequ�ncia.","e) itera��o, modularidade e frequ�ncia.","D"));

        qcl4.add(new Question("6 - [UFF 2009 - UFF] Segundo Pressman, em um sistema baseado em computador, � uma medida simples de confiabilidade:","a) Viola��o dos Padr�es de Programa��o (VPS);","b) Desvio Intencional das Especifica��es (IDS);","c) Tempo M�dio Entre Falhas (MTBF);","d) Erro na L�gica do Projeto (EDL);","e) Teste Incompleto ou Err�neo (IET).","C"));

        qcl4.add(new Question("7 - [CESGRANRIO 2006 - DECEA] Que paradigma da Engenharia de Software � seq�encial e sistem�tico, iniciando no n�vel de sistemas e se estendendo pela an�lise, projeto, codifica��o, teste e manuten��o?","a) Espiral.","b) Cl�ssico.","c) Prototipa��o.","d) T�cnicas de quarta gera��o.","e) Iterativo e incremental.","B"));

        qcl4.add(new Question("8 - [FCC 2008 - TCE-AL] A integridade de software � medida","a) em defeitos por KLOC (milhares de linhas de c�digo).","b) por sua usabilidade.","c) pelo mean-time-to-change ? MTTC.","d) por sua conectividade.","e) pela capacidade do sistema resistir a ataques � sua seguran�a.","E"));

        qcl4.add(new Question("9 - [FCC 2007 - TRE-SE] De acordo com o corpo de conhecimento da ger�ncia de projetos, internacionalmente aceito, uma das sa�das que comp�e o desenvolvimento do plano de projeto �","a) o Diagrama de Flecha.","b) o Modelo Param�trico.","c) o Gr�fico de Gantt.","d) a Estrutura Anal�tica do Projeto.","e) a Arquitetura do Software.","D"));

        qcl4.add(new Question("10 - [CESGRANRIO 2010 - ELETROBR�S] Sistemas de informa��es transformam, por interm�dio de suas fun��es, dados de entrada em dados de sa�da. No contexto da an�lise essencial, a modelagem funcional de um sistema pode ser representada graficamente atrav�s de diagramas de","a) contexto.","b) sequ�ncia.","c) fluxo de dados.","d) dep�sito de dados.","e) entidade e relacionamento.","C"));

        qcl5.add(new Question("1 - [IADES 2013 - EBSERH] Assinale a alternativa que n�o corresponde a uma das fases do processo de desenvolvimento, dirigido a testes (TDD).","a) Executar o teste, com os outros testes implementados, que rodar�o e fornecer�o o resultado de que o software est� sem problemas.","b) Escrever o teste para a funcionalidade e implementa��o.","c) Realizar a identifca��o do incremento de funcionalidade.","d) Implementar a funcionalidade e executar novamente o teste.","e) Implementar a pr�xima parte da funcionalidade, ap�s todos os testes terem sido executados, com sucesso.","A"));

        qcl5.add(new Question("2 - [IADES 2013 - EBSERH] Assinale a alternativa que corresponde �s tr�s estrat�gias de depura��o de software.","a) Estrat�gia da for�a bruta, estrat�gia do esfor�o e estrat�gia ascendente.","b) Estrat�gia da for�a bruta, estrat�gia do rastreamento e estrat�gia da elimina��o da causa.","c) Estrat�gia do rastreamento, estrat�gia de integra��o e estrat�gia ascendente","d) Estrat�gia do esfor�o, estrat�gia de integra��o e estrat�gia da elimina��o da causa.","e) Estrat�gia do rastreamento, estrat�gia de integra��o e estrat�gia da elimina��o da causa.","B"));

        qcl5.add(new Question("3 - [FGV 2010 - BADESC] De acordo com Pressman, a engenharia de software � baseada em camadas, com foco na qualidade. Essas camadas s�o:","a) m�todos, processo e teste.","b) ferramentas, m�todos e processo.","c) m�todos, constru��o, teste e implanta��o.","d) planejamento, modelagem, constru��o, valida��o e implanta��o.","e) comunica��o, planejamento, modelagem, constru��o e implanta��o.","B"));

        qcl5.add(new Question("4 - [FGV 2010 - BADESC] Segundo Pressman, um m�todo de planejamento de atividades � conhecido como:","a) CPM.","b) SLIM.","c) PERT.","d) KLOC.","e) COCOMO.","C"));

        qcl5.add(new Question("5 - [VUNESP 2009 - CETESB] Na An�lise Essencial, toda tecnologia usada para implementar as atividades essenciais e mem�ria essencial recebe o nome de","a) Ambiente.","b) Associa��o.","c) Encarna��o.","d) Legado.","e) Recurso.","C"));

        qcl5.add(new Question("6 - [VUNESP 2009 - CERESB] Na an�lise essencial, existem dois modelos para a abstra��o do neg�cio a ser documentado. Esses modelos s�o chamados de Modelo","a) Anal�tico e Modelo Estruturado.","b) Comportamental e Modelo Essencial.","c) Essencial e Modelo de Implementa��o.","d) de Ambiente e Modelo Comportamental.","e) de Implementa��o e Modelo Anal�tico.","C"));

        qcl5.add(new Question("7 - [CONSULPLAN 2006 - INB] S�o Caracter�sticas e/ou Fundamentos da An�lise Essencial, EXCETO:","a) Requisitos de Sistemas.","b) Sistemas de Resposta Planejada.","c) Ess�ncia do Sistema.","d) Permitir uma leitura do geral para o detalhe (\"top-down\").","e) Encarna��o da Ess�ncia/Sistema.","D"));

        qcl5.add(new Question("8 - [CONSULPLAN 2006 - INB] Ao se construir um Diagrama de Fluxo de Dados-DFD (na An�lise Essencial), pode-se afirmar que:","a) Todo processo � uma Primitiva Funcional.","b) Um Fluxo de Dados sempre dever� come�ar ou terminar em um Processo.","c) Fluxos de Dados podem ligar entre si duas ou mais Entidades Externas.","d) Uma Entidade Externa jamais poder� ser a representa��o de um outro sistema.","e) Uma Entidade Externa s� pode ser apresentada uma �nica vez.","B"));

        qcl5.add(new Question("9 - [CONSULPLAN 2006 - PREFEITURA DE NATAL-RN] As seguintes atividades fazem parte do processo de constru��o do Modelo Comportamental da An�lise Essencial, EXCETO:","a) Cria��o do Diagrama de Classes.","b) Cria��o de um processo para cada evento presente na lista/tabela de eventos.","c) Cria��o do modelo utilizando o Diagrama de Fluxo de Dados ? DFD.","d) Decomposi��o dos processos complexos em n�veis para minimizar a complexidade da modelagem.","e) Cria��o/atualiza��o do dicion�rio de dados.","A"));

        qcl5.add(new Question("10 - [CONSULPLAN 2006 - INB] Assinale a alternativa verdadeira de acordo com as seguintes afirmativas: I. A �rvore de Decis�o � uma das t�cnicas utilizadas para se especificar um processo na An�lise Essencial. II. A Tabela de Decis�o � uma das t�cnicas utilizadas para se especificar um processo na An�lise Essencial. III. A UML- Unified Modeling Language � uma das t�cnicas utilizadas para se especificar um processo na An�lise Essencial. Est�(�o) correta(s) apenas a(s) afirmativa(s):","a) I.","b) II.","c) III.","d) I e II.","e) I, II e III.","D"));
    }

    // level: numero de 1 a 5
    // question: numero de 1 a 20
    public Question getSpecificQuestionFromSpecificNormalLevel(int level, int question){
        if(question < 1 || question > 20)
            return null;
        switch (level) {
            case 1:
                return nql1.get(question-1);
            case 2:
                return nql2.get(question-1);
            case 3:
                return nql3.get(question-1);
            case 4:
                return nql4.get(question-1);
            case 5:
                return nql5.get(question-1);
            default:
                return null;
        }
    }
    // level: numero de 1 a 5
    public Question getRandomQuestionFromSpecificNormalLevel(int level){
        int max = 20,min = 1;
        Random rand = new Random();
        int rQuestion = (rand.nextInt((max - min) + 1) + min);
        switch (level){
            case 1:
                return nql1.get(rQuestion-1);
            case 2:
                return nql2.get(rQuestion-1);
            case 3:
                return nql3.get(rQuestion-1);
            case 4:
                return nql4.get(rQuestion-1);
            case 5:
                return nql5.get(rQuestion-1);
            default:
                return null;
        }
    }
    public Question getRandomQuestionFromRandomNormalLevel() {
        int maxQ = 20,minQ = 1;
        Random rand = new Random();
        int rQuestion = rand.nextInt((maxQ - minQ) + 1) + minQ;
        int maxL = 5, minL = 1;
        int rLevel = rand.nextInt((maxL - minL) + 1) + minL;
        switch (rLevel){
            case 1:
                return nql1.get(rQuestion-1);
            case 2:
                return nql2.get(rQuestion-1);
            case 3:
                return nql3.get(rQuestion-1);
            case 4:
                return nql4.get(rQuestion-1);
            case 5:
                return nql5.get(rQuestion-1);
            default:
                return nql1.get(0);
        }
    }


    // changeLevel: numero de 1 a 5
    // question: numero de 1 a 10
    public Question getSpecificQuestionFromSpecificChangeLevel(int changeLevel, int question){
        if(question < 1 || question > 10)
            return null;
        switch(changeLevel){
            case 1:
                return qcl1.get(question-1);
            case 2:
                return qcl2.get(question-1);
            case 3:
                return qcl3.get(question-1);
            case 4:
                return qcl4.get(question-1);
            case 5:
                return qcl5.get(question-1);
            default:
                return null;
        }
    }
    // changeLevel: numero de 1 a 5
    public Question getRandomQuestionFromChangeLevel(int changeLevel){
        int maxQ = 10,minQ = 1;
        Random rand = new Random();
        int rQuestion = rand.nextInt((maxQ - minQ) + 1) + minQ;
        switch(changeLevel){
            case 1:
                return qcl1.get(rQuestion-1);
            case 2:
                return qcl2.get(rQuestion-1);
            case 3:
                return qcl3.get(rQuestion-1);
            case 4:
                return qcl4.get(rQuestion-1);
            case 5:
                return qcl5.get(rQuestion-1);
            default:
                return null;
        }
    }
    public Question getRandomQuestionFromRandomChangeLevel() {
        int maxQ = 10,minQ = 1;
        Random rand = new Random();
        int rQuestion = rand.nextInt((maxQ - minQ) + 1) + minQ;
        int maxL = 5, minL = 1;
        int rLevel = rand.nextInt((maxL - minL) + 1) + minL;
        switch (rLevel){
            case 1:
                return qcl1.get(rQuestion-1);
            case 2:
                return qcl2.get(rQuestion-1);
            case 3:
                return qcl3.get(rQuestion-1);
            case 4:
                return qcl4.get(rQuestion-1);
            case 5:
                return qcl5.get(rQuestion-1);
            default:
                return qcl1.get(0);
        }
    }

}
